variables:
  datasource.servers:
    min: 1
    max: inf
    format: comma-separated
    type: string
    prompt-text: "Enter the Postgres database urls (including ports)"
  datasource.username:
    min: 1
    max: 1
    format: copy
    type: string
    prompt-text: "Enter the UAT Postgres database user name"
  tableau-rest-url:
    min: 1
    max: 1
    format: copy
    type: string
    prompt-text: "Enter the Tableau REST API url"
files:
  datasource: # lookup this file
    PostgresDataSource:
      jdbcUrl:  jdbc:postgresql://{datasource.servers}/workgroup?ssl=true&sslfactory=com.cibc.api.tableau.wbook.desc.PostgresSSLSocketFactory
      username: {datasource-username}
  proxy:
    hosts: {tableau-rest-url}
