use:
  client:
    tls:
      keyStore: '{client-keystore-name}'
variables:
  postgres-servers:
    min: 1
    max: inf
    output:
    - comma-separated
    type: string
    prompt-text: Enter the Postgres database urls (including ports)
  postgres-username:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the UAT Postgres database user name
  tableau-rest-url:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the Tableau REST API url
  tableau-username:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the Tableau functional ID username
  tableau-password:
    min: 1
    max: 1
    output:
    - encrypt
    type: string
    prompt-text: Enter the Tableau functional ID password
  postgres-password:
    min: 1
    max: 1
    output:
    - encrypt
    type: string
    prompt-text: Enter the Postgres database password
files:
  datasource:
    PostgresDataSource:
      jdbcUrl: jdbc:postgresql://{postgres-servers}/workgroup?ssl=true&sslfactory=com.cibc.api.tableau.wbook.desc.PostgresSSLSocketFactory
      username: '{postgres-username}'
  proxy:
    hosts: '{tableau-rest-url}'
  tableau:
    serverUrl: https://tableaussi-uat.cibcwm.com:443
    tableauUsername: '{tableau-username}'
  secret:
    tableauPassword: '{tableau-password}'
    postgresPassword: '{postgres-password}'
