variables:

  # Postgres database
  postgres-servers:     # this should be the same as the key (minus the first element) in config-server
    min: 1
    max: inf
    output:
    - comma-separated
    type: string
    replacement-strategy: regex   # values can be 'regex' or 'structural'
    prompt-text: Enter the Postgres database urls (including ports)
    files:
    - datasource

  postgres-username:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the UAT Postgres database user name
    files:
    - datasource

  postgres-password:
    min: 1
    max: 1
    output:
    - encrypt
    type: string
    prompt-text: Enter the Postgres database password
    files:
    - secret

  # Tableau web server
  tableau-serverUrl:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the Tableau REST API url
    files:
    - tableau
    - proxy

  tableau-username:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the Tableau functional ID username
    files:
    - tableau

  tableau-password:
    min: 1
    max: 1
    output:
    - encrypt
    type: string
    prompt-text: Enter the Tableau functional ID password
    files:
    - secret

  # Server keystore
  server-keystore-filename:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the filename of the server keystore
    files:
    - server

  server-keystore-pass:
    min: 1
    max: 1
    output:
    - copy
    type: encrypt
    prompt-text: Enter the server keystore password
    files:
    - secret

  server-keystore-privatekey-pass:
    min: 1
    max: 1
    output:
    - copy
    type: encrypt
    prompt-text: Enter the server keystore private key password
    files:
    - secret

  # Server truststore
  server-truststore-filename:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the filename of the server truststore
    files:
    - server

  server-truststore-pass:
    min: 1
    max: 1
    output:
    - copy
    type: encrypt
    prompt-text: Enter the server truststore password
    files:
    - server

  # Server security
  jwt-security:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enable (true) or disable (false) JWT verification security
    files:
    - security

  oauth-cert:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the name of the OAuth (Auth Server) certificate
    files:
    - security

  # Logging
  log-level:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Set the log level of the application ('fine' or 'debug' for testing, 'info' for production)
    files:
    - logback.xml

  # Client truststore
  client-truststore-pass:
    min: 1
    max: 1
    output:
    - copy
    type: encrypt
    prompt-text: Enter the client truststore password
    files:
    - secret

  client-truststore-filename:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Set the filename of the client truststore
    files:
    - client

  client-truststore-load:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Load the client truststore (true), or disbale loading (false)
    files:
    - client

  # Client keystore
  client-keystore-filename:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Set the filename of the client keystore
    files:
    - client

  client-keystore-load:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Load the client keystore (true), or disbale loading (false)
    files:
    - client

  client-keystore-pass:
    min: 1
    max: 1
    output:
    - copy
    type: encrypt
    prompt-text: Enter the client keystore password
    files:
    - secret

  client-keystore-privatekey-pass:
    min: 1
    max: 1
    output:
    - copy
    type: encrypt
    prompt-text: Enter the client keystore private key password
    files:
    - secret
