# Use a value from an existing part of the config
use:
  client:
    tls:
      keyStore: '{client-keystore-name}'

variables:

  postgres-servers:     # this should be the same as the key (minus the first element) in config-server
    min: 1
    max: inf
    output:
    - comma-separated
    type: string
    replacement-strategy: regex   # values can be 'regex' or 'structural'
    prompt-text: Enter the Postgres database urls (including ports)
    files:
    - datasource

  postgres-username:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the UAT Postgres database user name
    files:
    - datasource

  tableau-rest-url:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the Tableau REST API url
    files:
    - tableau
    - proxy

  tableau-username:
    min: 1
    max: 1
    output:
    - copy
    type: string
    prompt-text: Enter the Tableau functional ID username
    files:
    - tableau

  tableau-password:
    min: 1
    max: 1
    output:
    - encrypt
    type: string
    prompt-text: Enter the Tableau functional ID password
    files:
    - secret

  postgres-password:
    min: 1
    max: 1
    output:
    - encrypt
    type: string
    prompt-text: Enter the Postgres database password
    files:
    - secret
