# This is the configuration for Http2Client
---
# Settings for TLS
tls:
  # if the server is using self-signed certificate, this need to be false. If true, you have to use CA signed certificate
  # or load truststore that contains the self-signed cretificate.
  verifyHostname: true
  # trust store contains certifictes that server needs. Enable if tls is used.
  loadTrustStore: true
  # trust store location can be specified here or system properties javax.net.ssl.trustStore and password javax.net.ssl.trustStorePassword
  trustStore: client.truststore
  # key store contains client key and it should be loaded if two-way ssl is uesed.
  loadKeyStore: false
  # key store location
  keyStore: client.keystore

# Settings for OAuth2 server communication
# oauth:
#   token:
#     # The scope token will be renewed automatically 1 minutes before expiry
#     tokenRenewBeforeExpired: 60000
#     # if scope token is expired, we need short delay so that we can retry faster.
#     expiredRefreshRetryDelay: 2000
#     # if scope token is not expired but in renew windown, we need slow retry delay.
#     earlyRefreshRetryDelay: 4000
#     # token server url. The default port number for token service is 6882.
#     server_url: http://localhost:6882
#     serviceId: com.networknt.oauth2-token-1.0.0
#     authorization_code:
#       # token endpoint for authorization code grant
#       uri: "/oauth2/token"
#       # client_id for authorization code grant flow. client_secret is in secret.yml
#       client_id: 6fde9971-1233-4c96-b949-3c4786047dba
#       redirect_uri: https://localhost:8080/authorization_code
#       scope:
#       - training.customers.read
#       - training.accounts.read
#       - training.transacts.read
#     client_credentials:
#       # token endpoint for client credentials grant
#       uri: "/oauth2/token"
#       # client_id for client credentials grant flow. client_secret is in secret.yml
#       client_id: 6fde9971-1233-4c96-b949-3c4786047dba
#       scope:
#       - training.customers.read
#       - training.accounts.read
#       - training.transacts.read
#   key:
#     server_url: http://localhost:6886
#     serviceId: com.networknt.oauth2-key-1.0.0
#     uri: "/oauth2/key"
#     client_id: 6fde9971-1233-4c96-b949-3c4786047dba
