# This file contains all the secrets for the server and client in order to manage and
# secure all of them in the same place. In Kubernetes, this file will be mapped to
# Secrets and all other config files will be mapped to mapConfig

#----------------------------------------

# Sever section

# Key store password, the path of keystore is defined in server.yml
# TABLEAU
serverKeystorePass: CRYPT:mBgB9yFIQqlO/XfR7CYtESYx59ZIlDLMxnpCrKTNb3U=
#
# NEO4J
# serverKeystorePass: CRYPT:fXdjMae8UQ2zIb/NjiwdSzu1e87+apZqze24m2N/krM=

# Key password, the key is in keystore
# TABLEAU
serverKeyPass: CRYPT:S4OG96BgSWlvrsBfjk+5XTlFvezdcfwxbjiJjhd+SUM=
#
# NEO4J
# serverKeystorePass: CRYPT:vH/paL3aWoA4gQuWjrZxWf0RkBJ49Lrc2rCe/VT8uZ8=

# Trust store password, the path of truststore is defined in server.yml
# TABLEAU / NEO4J
serverTruststorePass: CRYPT:EqB1IcAYQmb68p3J1xoOJN7RUqic274IMAfAeaIS2nU=

#----------------------------------------

# Client section

# Key store password, the path of keystore is defined in server.yml
# TABLEAU / NEO4J
clientKeystorePass: CRYPT:QK8k+LN+nMWio6t021U+e7r5d0vJWlNWwL+wJczoQbo=

# Key password, the key is in keystore
# TABLEAU / NEO4J
clientKeyPass: CRYPT:TBfCCDvbjzsVbppNB2nAzkAdwwey8+BM6sqKmgoU0p4=

# Trust store password, the path of truststore is defined in server.yml
# TABLEAU / TABLEAU2 / NEO4J
clientTruststorePass: CRYPT:c1Ht5IpGIfn/GoYY16gm7Bgsvo9HLHh8xzV0SO+n//I=

#----------------------------------------

# OAuth section

# Authorization code client secret for OAuth2 server
# TABLEAU / NEO4J
authorizationCodeClientSecret: CRYPT:dimq/3BeTpo9lXGiuil3t5AHgd2nrX6tjzIKLeBYzQpUvePjKRBj2RKxnWe7s2Fr

# Client credentials client secret for OAuth2 server
# TABLEAU / NEO4J
clientCredentialsClientSecret: CRYPT:yWJffnbsJogM+6NLHdHxEtaWqvHZ2/5cAXWoJBaPbJ+iLwIhar1N6WavefxxUMGw

# Key distribution client secret for OAuth2 server
# TABLEAU / NEO4J
keyClientSecret: CRYPT:zw3iFZoblgxRGiWFBV2tF0HLVSEsbM92VG6SimeeCh50w8vRZ0w+0DozLzRohNvz

# Tableau Password used by light-proxy with Tableau backend only
#tableauPassword: CRYPT:cSexKrTMDN9QMdtr+l6qKCpp8z7FWifTA+NmwZ38RT8=
#tableauPassword: CRYPT:ioNF/DjwKke6bwSBzXeptEuqsHtZRfTas6eW8O772d0=
tableauPassword: CRYPT:BWClSzlME0Dgx47ZdW6CiH55IXLlKAE7c03fmO9cUBo=

# Postgres Password
postgresPassword: CRYPT:RupCaSsLjxxMbnzE3EetDYdYXhuujsRLUezTf0xA1+k=

# Consul service registry and discovery

# Consul Token for service registry and discovery
# consulToken: the_one_ring
